REMOTE_1_AGENT_NAME = "CMS_Agent"
REMOTE_1_AGENT_VERSION = "1.0.0"
REMOTE_1_AGENT_HOST = "localhost"
REMOTE_1_AGENT_PORT = 10002
REMOTE_1_AGENT_URL = "http://localhost:10002"
REMOTE_1_AGENT_DEFAULT_USER_ID = "database_agent_user"
REMOTE_1_AGENT_DATABASE_API_URL = "http://192.168.1.85:5001/listalltabledata"
REMOTE_1_AGENT_DATABASE_DBNAME = "dev_cms"
# REMOTE_1_AGENT_DATABASE_DBNAME = "cms_prod"

HOST_AGENT_NAME = "Host_Agent"

MODEL="gemini-2.0-flash"
